/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppCamera {}
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface NoteDetail {
    'data': any;
  }
}

declare global {


  interface HTMLAppCameraElement extends Components.AppCamera, HTMLStencilElement {}
  var HTMLAppCameraElement: {
    prototype: HTMLAppCameraElement;
    new (): HTMLAppCameraElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLNoteDetailElement extends Components.NoteDetail, HTMLStencilElement {}
  var HTMLNoteDetailElement: {
    prototype: HTMLNoteDetailElement;
    new (): HTMLNoteDetailElement;
  };
  interface HTMLElementTagNameMap {
    'app-camera': HTMLAppCameraElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'note-detail': HTMLNoteDetailElement;
  }
}

declare namespace LocalJSX {
  interface AppCamera {}
  interface AppHome {}
  interface AppProfile {
    'name'?: string;
  }
  interface AppRoot {}
  interface NoteDetail {
    'data'?: any;
  }

  interface IntrinsicElements {
    'app-camera': AppCamera;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'note-detail': NoteDetail;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-camera': LocalJSX.AppCamera & JSXBase.HTMLAttributes<HTMLAppCameraElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'note-detail': LocalJSX.NoteDetail & JSXBase.HTMLAttributes<HTMLNoteDetailElement>;
    }
  }
}


